### ISSUE TITLE
Unable to build the app environment

### ISSUE THREAD

**Issue by m1-key** [scorelab/TrackPal#52]
![error2](https://user-images.githubusercontent.com/39923784/73126225-0ead2180-3fd6-11ea-947d-48d02de87a53.JPG)

I am getting this error , how to resolve this. Please help

**Comment by viradhanus** [comment]
The issue seems to be when configuring the project with androidX. You can try with [this PR](https://github.com/scorelab/TrackPal/pull/44). But still there are issues. Try to figure them out

**Comment by shehand** [comment]
@m1-key can you upload the full stacktrace of the error?

**Comment by m1-key** [comment]
@shehand  I fixed the above issue , but now got new error..

![erro3](https://user-images.githubusercontent.com/39923784/73176012-775ce100-4131-11ea-9984-4f8e811af90a.JPG)

Please help to build the app so that I can start contributing to the project.

**Comment by m1-key** [comment]
> Task :app:transformClassesWithMultidexlistForDebug FAILED
D8: Program type already present: android.support.v4.media.MediaBrowserCompat$CallbackHandler

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives:
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.media.MediaBrowserCompat$CallbackHandler

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: Error while generating the main dex list:
Error while merging dex archives:
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: android.support.v4.media.MediaBrowserCompat$CallbackHandler
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more
Caused by: com.android.build.api.transform.TransformException: Error while generating the main dex list:
Error while merging dex archives:
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: android.support.v4.media.MediaBrowserCompat$CallbackHandler
        at com.android.build.gradle.internal.transforms.D8MainDexListTransform.transform(D8MainDexListTransform.kt:147)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        ... 44 more
Caused by: com.android.builder.multidex.D8MainDexList$MainDexListException: Error while merging dex archives:
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: android.support.v4.media.MediaBrowserCompat$CallbackHandler
        at com.android.builder.multidex.D8MainDexList.getExceptionToRethrow(D8MainDexList.java:107)
        at com.android.builder.multidex.D8MainDexList.generate(D8MainDexList.java:95)
        at com.android.build.gradle.internal.transforms.D8MainDexListTransform.transform(D8MainDexListTransform.kt:131)
        ... 47 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:70)
        at com.android.tools.r8.utils.ExceptionUtils.withMainDexListHandler(ExceptionUtils.java:53)
        at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:118)
        at com.android.builder.multidex.D8MainDexList.generate(D8MainDexList.java:93)
        ... 48 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: android.support.v4.media.MediaBrowserCompat$CallbackHandler
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:89)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:60)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:64)
        ... 51 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
105 actionable tasks: 2 executed, 103 up-to-date

**Comment by viradhanus** [comment]
> @shehand I fixed the above issue , but now got new error..
> 
> ![erro3](https://user-images.githubusercontent.com/39923784/73176012-775ce100-4131-11ea-9984-4f8e811af90a.JPG)
> 
> Please help to build the app so that I can start contributing to the project.

Don't wait for someone to fix the issue. Try it.. then all can contribute :blush:

**Comment by viradhanus** [comment]
> ![erro3](https://user-images.githubusercontent.com/39923784/73176012-775ce100-4131-11ea-9984-4f8e811af90a.JPG)
> 
> Please help to build the app so that I can start contributing to the project.

Don't wait for someone to fix the issue. Try it.. then all can contribute :blush:

**Comment by shehand** [comment]
Ok now, this has to be something wrong with Gradle build. Looks like the Gradle you are using is incompatible with the Gradle that is used to build the application.

**Comment by m1-key** [comment]
@shehand Sir , then what I have to do to run it on my system ? Any suggestions

**Comment by shehand** [comment]
Try to search a solution in google. Most probably you will get one

**Comment by m1-key** [comment]
> Ok now, this has to be something wrong with Gradle build. Looks like the Gradle you are using is incompatible with the Gradle that is used to build the application.

Which version of gradle was used to build this project ?

**Comment by m1-key** [comment]
![error4](https://user-images.githubusercontent.com/39923784/73270186-308beb80-4204-11ea-9d01-4c021875e601.JPG)
 
This might be the last error, because it happened at 98% , how to rectify this ? I created the debug.keystore using ``` keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000``` and then renamed it as ```my-release-key.keystore``` . Still got this error. Please help or guide how to rectify this.

**Comment by viradhanus** [comment]
Then you have to edit  _**gradle.properties**_ file like bellow

MYAPP_RELEASE_STORE_FILE=my-release-key.keystore
MYAPP_RELEASE_KEY_ALIAS=android
MYAPP_RELEASE_STORE_PASSWORD=android
MYAPP_RELEASE_KEY_PASSWORD=android

_or you can use this command and generate the my-release-key.keystore file straightforwardly :blush:_

keytool -genkey -v -keystore my-release-key.keystore -storepass 000000 -alias my-key-alias -keypass 000000 -keyalg RSA -keysize 2048 -validity 10000

Hope you got it :100:

**Comment by m1-key** [comment]
Thanks a lot sir, finally App build was successful. But now I have encountered a new error 

![WhatsApp Image 2020-01-28 at 21 33 24](https://user-images.githubusercontent.com/39923784/73281597-3985b880-4216-11ea-97c9-a59e28a4582f.jpeg)

Since everything seems right , still this error pops up , how to tackle this ? 
I searched for this , all solutions eventually stated that we have to update Manifest file by including 
```<meta-data android:name="com.facebook.sdk.ApplicationId"
          android:value="@string/facebook_app_id"/>```  
which is already present. And strings.xml file is also there with the id value

**Comment by viradhanus** [comment]
@m1-key 
Can you post your environment info (run `react-native info`) and Java version?

**Comment by m1-key** [comment]
![envi](https://user-images.githubusercontent.com/39923784/73290918-38a85300-4225-11ea-81d6-9fce3e6717bf.JPG)

**Comment by viradhanus** [comment]
@m1-key 
Hmm requirements seems to be ok but can't figure out without proper googling 😊  Will update if I got sth 👍

**Comment by m1-key** [comment]
@viradhanus  I changed few things in the code , I added two lines ( the highlighted ones in the image) , which removed the error but the app crashes as soon as build is successful.
![image](https://user-images.githubusercontent.com/39923784/73357911-78be1300-42c3-11ea-8608-f511b4f80ae1.JPG)

**Comment by viradhanus** [comment]
@m1-key 
Did you try to upgrade the react native version of the project ❔

**Comment by thomas2308** [comment]
> @m1-key
> Did you try to upgrade the react native version of the project

No

**Comment by viradhanus** [comment]
@m1-key 
Lets try to upgrade the version as well.. Hopefully it will solve all these issues 😊
