### ISSUE TITLE
ERROR: Gradle DSL method not found: 'classpath()'

### ISSUE THREAD

**Issue by thilinaviraj** [scorelab/TrackPal#57]
I tried to build the project with android studio. Initially, the npm install was failed due to mismatch in the firebase versions configured in the project. Once updated with the latest version, the npm install could be completed. But now I'm facing below errors when trying to build the android app. 
Updated the gradle version to 5.6.4 as well
![image](https://user-images.githubusercontent.com/9677359/80899210-26114e80-8d2b-11ea-8280-28afdbfb2da7.png)

**Comment by shehand** [comment]
@thilinaviraj are you trying to build the app by using Android Studio without using React-Native?

**Comment by shehand** [comment]
@thilinaviraj what was the output when you ran ```npx react-native run-android```

**Comment by thilinaviraj** [comment]
@shehand pls find below output

SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/
: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (D:\BugBounty\Exported\TrackPal\node_modules\metro-config\
src\defaults\blacklist.js:34:10)
    at getBlacklistRE (D:\BugBounty\Exported\TrackPal\node_modules\react-na
tive\local-cli\util\Config.js:56:10)
    at Object.<anonymous> (D:\BugBounty\Exported\TrackPal\node_modules\reac
t-native\local-cli\util\Config.js:71:20)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Module._compile (D:\BugBounty\Exported\TrackPal\node_modules\pirates
\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.newLoader [as .js] (D:\BugBounty\Exported\TrackPal\node_modul
es\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)

**Comment by shehand** [comment]
OK. I'm a bit confused now. Did you follow all the steps in the guide? Because I'm not getting such an error.

**Comment by thilinaviraj** [comment]
Yes. Possible to update the repo with the latest set of dependencies?

**Comment by thilinaviraj** [comment]
This is due to an issue in the latest node modules. You can fix it by updating your blacklist.js file as below. (Just adding backslashes)

var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

**Comment by shehand** [comment]
I've updated the docs of TrackPal. This issue should be solved by this PR
